# port
server.port=8086

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# WebCrud
entity.package=tech.cvezga.chargingstation.entity

# db
spring.datasource.url=jdbc:postgresql://localhost:5432/chargingstation
spring.datasource.username=${charging_station_db_username}
spring.datasource.password=${charging_station_db_password}